### ISSUE TITLE
When enabling packetparser retina pods go into CrashLoopBackOff

### ISSUE THREAD

**Issue by boniek83** [microsoft/retina#321]
**Describe the bug**
After adding enablePodLevel: true and packetparser to the default list of plugins (default as of v0.0.9 version of helm chart) pods go into CrashLoopBackOff and I get following message in logs:

```
ts=2024-04-26T23:56:36.036Z level=panic caller=controllermanager/controllermanager.go:119 msg="Error running controller manager" goversion=go1.21.8 os=linux arch=amd64 numcores=64 hostname=worker-4.srv podname=retina-agent-7qdbw version=v0.0.2 apiserver=https://10.40.0.1:443 plugins=dropreason,packetforward,linuxutil,dns,packetparser error="failed to reconcile plugin dropreason: context canceled" errorVerbose="context canceled\nfailed to reconcile plugin dropreason\ngithub.com/microsoft/retina/pkg/managers/pluginmanager.(*PluginManager).Start\n\t/go/src/github.com/microsoft/retina/pkg/managers/pluginmanager/pluginmanager.go:169\ngithub.com/microsoft/retina/pkg/managers/controllermanager.(*Controller).Start.func1\n\t/go/src/github.com/microsoft/retina/pkg/managers/controllermanager/controllermanager.go:109\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:78\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650"

panic: Error running controller manager
goroutine 468 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x1?, 0x0?, {0x0?, 0x0?, 0xc0019a3900?})
	/go/pkg/mod/go.uber.org/zap@v1.26.0/zapcore/entry.go:196 +0x54
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0019daa90, {0xc001a27040, 0x1, 0x1})
	/go/pkg/mod/go.uber.org/zap@v1.26.0/zapcore/entry.go:262 +0x3ec
go.uber.org/zap.(*Logger).Panic(0xc0014e33c0?, {0x2b4d495?, 0x0?}, {0xc001a27040, 0x1, 0x1})
	/go/pkg/mod/go.uber.org/zap@v1.26.0/logger.go:284 +0x51
github.com/microsoft/retina/pkg/managers/controllermanager.(*Controller).Start(0xc00060fd10, {0x2f0a790?, 0xc000c34000?})
	/go/src/github.com/microsoft/retina/pkg/managers/controllermanager/controllermanager.go:119 +0x28c
created by main.main in goroutine 1
	/go/src/github.com/microsoft/retina/controller/main.go:290 +0x28d0
```

**Platform (please complete the following information):**

- OS: AlmaLinux 8.7
- Kubernetes Version: 1.23
- Host: self-host
- Retina Version: helm chart v0.0.9

**Comment by rbtr** [comment]
Hey @boniek83, I notice you said you installed v0.0.9, but the log shows you're running Retina v0.0.2 (`version=v0.0.2`). Did you install it using our [Quickstart Instructions](https://retina.sh/docs/installation/setup#basic-mode)? Can you upgrade to v0.0.9 and let me know if you still encounter this issue? I think it has already been fixed.

**Comment by boniek83** [comment]
Indeed I was running v0.0.2 (issue with helm chart?) I've bumped up tag to v0.0.9 and it still doesn't work:
```
ts=2024-04-30T20:15:32.306Z level=panic caller=controllermanager/controllermanager.go:119 msg="Error running controller manager" goversion=go1.22.2 os=linux arch=amd64 numcores=64 hostname=worker-8.srv podname=retina-agent-c9n5g version=v0.0.9 apiserver=https://10.40.0.1:443 plugins=dropreason,packetforward,linuxutil,dns,packetparser error="failed to start plugin manager, plugin exited: failed to start plugin packetparser: interface eth0 of type device not found" errorVerbose="interface eth0 of type device not found\nfailed to start plugin packetparser\ngithub.com/microsoft/retina/pkg/managers/pluginmanager.(*PluginManager).Start.func1\n\t/go/src/github.com/microsoft/retina/pkg/managers/pluginmanager/pluginmanager.go:174\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1695\nfailed to start plugin manager, plugin exited\ngithub.com/microsoft/retina/pkg/managers/pluginmanager.(*PluginManager).Start\n\t/go/src/github.com/microsoft/retina/pkg/managers/pluginmanager/pluginmanager.go:186\ngithub.com/microsoft/retina/pkg/managers/controllermanager.(*Controller).Start.func1\n\t/go/src/github.com/microsoft/retina/pkg/managers/controllermanager/controllermanager.go:109\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1695"
panic: Error running controller manager
goroutine 498 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x1?, 0x0?, {0x0?, 0x0?, 0xc0037e0140?})
	/go/pkg/mod/go.uber.org/zap@v1.26.0/zapcore/entry.go:196 +0x54
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc002db20d0, {0xc00286a5c0, 0x1, 0x1})
	/go/pkg/mod/go.uber.org/zap@v1.26.0/zapcore/entry.go:262 +0x24e
go.uber.org/zap.(*Logger).Panic(0xc0006a6ec0?, {0x2b83a07?, 0x0?}, {0xc00286a5c0, 0x1, 0x1})
	/go/pkg/mod/go.uber.org/zap@v1.26.0/logger.go:284 +0x51
github.com/microsoft/retina/pkg/managers/controllermanager.(*Controller).Start(0xc0008231d0, {0x2f56630?, 0xc00056db80?})
	/go/src/github.com/microsoft/retina/pkg/managers/controllermanager/controllermanager.go:119 +0x27c
created by main.main in goroutine 1
	/go/src/github.com/microsoft/retina/controller/main.go:290 +0x28a5
```

**Comment by rbtr** [comment]
ah
> interface eth0 of type device not found

this is the same issue mentioned here: https://github.com/microsoft/retina/issues/115#issuecomment-2031313354
and should be fixed by https://github.com/microsoft/retina/pull/215
